### ISSUE TITLE
Cannot set locale

### ISSUE THREAD

**Issue by yajo** [CentOS/sig-cloud-instance-images#10]
Hello, I'm trying to enable the `es_ES.utf-8` locale inside a container, but seems not possible right now.

To reproduce:

```
$ docker run -it --rm centos bash -c 'LC_ALL=es_ES.utf-8; LC_ALL=es_ES; LC_ALL=es; ls /usr/share/i18n/locales/es_ES*; locale -a | grep es || echo "not found es :("'
bash: warning: setlocale: LC_ALL: cannot change locale (es_ES.utf-8): No such file or directory
bash: warning: setlocale: LC_ALL: cannot change locale (es_ES): No such file or directory
bash: warning: setlocale: LC_ALL: cannot change locale (es): No such file or directory
/usr/share/i18n/locales/es_ES  /usr/share/i18n/locales/es_ES@euro
not found es :(
```

**Comment by jperrin** [comment]
Languages currently take up about 1/3 of the container size, so we stripped several out to make the containers smaller. It looks like you're trying to use one of the ones we have removed. 

If you 'yum reinstall glibc' you'll have all the locales back, at the cost of a bit more disk space.

**Comment by yajo** [comment]
I imagined something like that, but could not find any docs about it.

**Comment by yajo** [comment]
Actually I had to `yum -y reinstall glibc-common`.

**Comment by jperrin** [comment]
ah, you're correct. I gave you the wrong package name. Sorry. Marking this as closed now since you have it sorted.

**Comment by bananayong** [comment]
That's helpful to me. Thanks!!

**Comment by gdubicki** [comment]
Above solution didn't help me. But following workaround from https://github.com/CentOS/sig-cloud-instance-images/issues/71 did.
