### ISSUE TITLE
how to iload the latest docer image

### ISSUE THREAD

**Issue by kuncao** [CentOS/sig-cloud-instance-images#101]
Hello every gru
When I down load the latest centos7 docker images from the following url:
https://github.com/CentOS/sig-cloud-instance-images/blob/79db851f4016c283fb3d30f924031f5a866d51a1/docker/centos-7-docker.tar.xz
then xz the file as 
xz -d centos-7-docker.tar.xz
when load the image into the docker repository
docker load -i centos-7-docker.tar
open /var/lib/docker/tmp/docker-import-894421180/dev/json: no such file or directory

How to load the centos 7 image?
or there is something missing  of my operation?
Thanks a lot

**Comment by kuncao** [comment]
FROM scratch
MAINTAINER caokun caokun.nj@huawei.com
ADD centos-7-docker.tar.xz /
#ADD centos-7.1503-20150330_1749-docker.tar.xz /
CMD ["/bin/bash"]

**Comment by jperrin** [comment]
There's already a dockerfile in the repository, why are you doing it this way? 

Also, why not just `docker pull centos:7`
