### ISSUE TITLE
Wrong kernel versions for 6.7 and 6.8?

### ISSUE THREAD

**Issue by suranap** [CentOS/sig-cloud-instance-images#109]
Shouldn't the docker images for CentOS 6.* use kernel 2.*? [Over here](http://vault.centos.org/6.7/os/Source/SPackages/), the source package for 6.7 uses kernel-2.6.32-573.el6.src.rpm. And my company's ancient Redhat 6.7 server is using that same 2.6.32 kernel. 

Docker image `docker run --rm -ti centos:6.8`: 
```
# uname -a 
Linux cfd2406377ac 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/redhat-release 
CentOS release 6.8 (Final)
```
Docker image `$ docker run -ti --rm centos:6.7`:
```
# uname -a
Linux eab483333731 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/redhat-release 
CentOS release 6.7 (Final)
```

**Comment by jperrin** [comment]
Docker containers aren't like a vm. They don't include a kernel, because the container is just a name-spaced process running on the host. The 4.9 kernel you see is whatever your docker host is using.
