### ISSUE TITLE
centos kernel version for docker image

### ISSUE THREAD

**Issue by kasured** [CentOS/sig-cloud-instance-images#11]
I must be missing something, but why running the container from the 'centos:7' image gives me the following output for "uname -r"
2.6.32-504.8.1.el6.x86_64

However, centos-release gives me 7.0.1406 (Core)

**Comment by jperrin** [comment]
Docker isn't a vm. it's a container. It's showing you the host's kernel, because that's what its using. 

So it's using your host's kernel, which is el6.
