### ISSUE TITLE
pip uninstall chardet causes file corruption in pip's uninstall /tmp directory

### ISSUE THREAD

**Issue by krehm** [CentOS/sig-cloud-instance-images#110]
Here is the Dockerfile that eventually results in a corrupt directory:

FROM centos:7
RUN set -x && \
    yum install -y epel-release && \
    yum install -y python-pip
ENTRYPOINT [ "/usr/bin/bash" ]

After creating the image, I start a container using:
    docker run --rm -it image-id
and then I enter the pip command:
    pip uninstall chardet
which fails every time with a python backtrace and:
    OSError: [Errno 2] No such file or directory: '/tmp/pip-uninstall-4YoV0P/usr/bin/chardetect'

If I do a 'ls -l' on that directory, I see that it is corrupt, the chardetect file in that directory has been unlinked, the inode is unused, but the directory still contains the dirent for the deleted file:

[root@d837c8f69902 /]# ls -l /tmp/pip-uninstall-4YoV0P/usr/bin/
ls: cannot access /tmp/pip-uninstall-4YoV0P/usr/bin/chardetect: No such file or directory
total 0 
c????????? ? ? ? ?            ? chardetect

This is not an xfs problem, my xfs filesystem has ftype=1, and another person sees the same failures using ext4 filesystems for docker.  The corruption occurs when pip calls shutil.rmtree(path) to delete the uninstall temp directory.  rmtree() recurses down into the bin directory, then calls os.remove(path) to remove the single file chardetect.   Just before that call the directory is sane, right after that call, the directory is corrupt.

rmtree() then continues, it assumes the ../usr/bin directory should be empty now and does a rmdir() on bin, which fails saying the directory is not empty.  An error handler is called, but it can only handle the case where a file to be removed has no write permissions, so the recovery doesn't work, and pip fails with the traceback at that point.

We have seen this problem repeatedly on a number of servers, anything which causes chardet to be uninstalled or upgraded (e.g. "pip install docker" or "pip install httpie') results in the same corrupt directory.   I also tried using the centos7.4.1708 and centos7.3.1611 images at library/centos instead of centos:7, same result.  Could others try to duplicate this?   I don't know what debugging steps to try next.

Here is the full output from one uninstall attempt:

root@caribou11 sma-utility]# docker run --rm -it 1c56b90aefef
[root@d837c8f69902 /]# pip uninstall chardet
Uninstalling chardet-2.2.1:
  Would remove:
    /usr/bin/chardetect
    /usr/lib/python2.7/site-packages/chardet
    /usr/lib/python2.7/site-packages/chardet-2.2.1-py2.7.egg-info
Proceed (y/n)? y
  Successfully uninstalled chardet-2.2.1
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/_internal/commands/uninstall.py", line 71, in run
    uninstall_pathset.commit()
  File "/usr/lib/python2.7/site-packages/pip/_internal/req/req_uninstall.py", line 270, in commit
    self.save_dir.cleanup()
  File "/usr/lib/python2.7/site-packages/pip/_internal/utils/temp_dir.py", line 81, in cleanup
    rmtree(self.path)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/lib/python2.7/site-packages/pip/_vendor/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python2.7/site-packages/pip/_vendor/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 108, in rmtree
    onerror=rmtree_errorhandler)
  File "/usr/lib64/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib64/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib64/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 116, in rmtree_errorhandler
    if os.stat(path).st_mode & stat.S_IREAD:
OSError: [Errno 2] No such file or directory: '/tmp/pip-uninstall-4YoV0P/usr/bin/chardetect'
[root@d837c8f69902 /]# ls -l /tmp/pip-uninstall-4YoV0P/usr/bin/
ls: cannot access /tmp/pip-uninstall-4YoV0P/usr/bin/chardetect: No such file or directory
total 0
c????????? ? ? ? ?            ? chardetect
[root@d837c8f69902 /]#

**Comment by ghost** [comment]
Hi @krehm,

I tried your steps, but i can't reproduce your issue. It seems not to be an issue with the CentOS image at all.

```
$ cat Dockerfile.issue110
FROM centos:7
RUN set -x && \
yum install -y epel-release && \
yum install -y python-pip
ENTRYPOINT [ "/usr/bin/bash" ]

$ docker build -f Dockerfile.issue110 -t centos:issue110 .

$ docker run --rm -it centos:issue110 -c "pip uninstall chardet"
Uninstalling chardet-2.2.1:
  /usr/bin/chardetect
  /usr/lib/python2.7/site-packages/chardet
  /usr/lib/python2.7/site-packages/chardet-2.2.1-py2.7.egg-info
Proceed (y/n)? y
  Successfully uninstalled chardet-2.2.1
You are using pip version 8.1.2, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

What is the output of your `docker info` page?

Maybe it is an issue with your Docker Installation? Could you stop your Docker Engine (e.g. `systemctl stop docker`) and move your `/var/lib/docker` directory (with all your volumes, images, ..) to a different place (e.g. `mv /var/lib/docker /var/lib/docker.bak`)? And start Docker, again? Could you reproduce it after that? Maybe a Docker upgrade harmed something.

A similar problem could also be triggered by a security feature like AppAmor oder Selinux, is something enable on your host system? Could you check you system log files if such an application is preventing the `pip` command?

**Comment by krehm** [comment]
Sorry about the delay...   Turning off selinux didn't help.  But I have found that I can duplicate the problem on several docker hosts which all happen to be running CentOS 7.2, but if I instead use a docker host running CentOS 7.5, the problem is gone.    So it appears to be a host OS problem, not a container problem.   I can live with using more current docker host OSs, so I'm closing this ticket.   Thanks for taking a look.
