### ISSUE TITLE
provide oficial image for 7.5.1804

### ISSUE THREAD

**Issue by ninrod** [CentOS/sig-cloud-instance-images#113]
Provide an oficial image for the newest stable version `7.5.1804` as per the [announcement](https://www.centos.org/forums/viewtopic.php?f=9&t=67046&sid=39a8d8cdcfa16443fea32234e960a39e)

**Comment by dcsouthwick** [comment]
_spins_ of centos have 7.5 images available...

`docker pull cern/cc7-base`

**Comment by ninrod** [comment]
thanks. I'd rather have the official. Is there any ETA or planned release?

**Comment by matttbe** [comment]
The official image is now available thanks to @jperrin :
- https://github.com/CentOS/sig-cloud-instance-images/blob/CentOS-7.5.1804/docker/Dockerfile
- https://hub.docker.com/_/centos/

I don't know who can close this issue.

**Comment by ninrod** [comment]
thanks @matttbe, I can.
