### ISSUE TITLE
default CMD

### ISSUE THREAD

**Issue by yosifkit** [CentOS/sig-cloud-instance-images#12]
This is just a minor issue, but it would be nice if the Dockerfiles specified `CMD ["/bin/bash"]` like the other base images.

**Comment by jperrin** [comment]
Yep. that's very doable. I'll build that into the next round.

**Comment by yosifkit** [comment]
Awesome!

**Comment by jperrin** [comment]
Thoughts on baking in 'standard' volumes as well such as /var/log? is there a 'best practice' yet for base containers?

**Comment by tianon** [comment]
I'd say the difference with VOLUME vs CMD is that CMD is trivially
overwritten, where VOLUME is (currently) forever.

**Comment by tianon** [comment]
You can even `CMD []` to just completely unset the default command.

**Comment by tianon** [comment]
See also https://github.com/docker-library/official-images/pull/497#issuecomment-75575183, the relevant bit of I'll copy here:

> ... adding `/run` and `/tmp` as volumes here will potentially break a non-zero number of `Dockerfile`s depending on this image, since there's no way to undo a `VOLUME` definition and it makes that directory no longer committable (and thus stuck "empty" for all dependent images), ...

**Comment by jperrin** [comment]
yeah. We currently ship with systemd ripped out, however the future may look more like -> https://github.com/fedora-cloud/docker-brew-fedora/blob/master/Dockerfile

So exactly the directories you mention may be in play.

**Comment by jperrin** [comment]
I may end up doing another base image just for systemd functionality. We'll see.

**Comment by tianon** [comment]
You have control of the "centos" namespace on the hub, right?
 "centos/systemd" is something I'd personally love to see be a thing :+1:

**Comment by jperrin** [comment]
I do, and I can certainly do that, but I was thinking more for
'official' containers.

On 03/05/2015 07:10 PM, Tianon Gravi wrote:

> You have control of the "centos" namespace on the hub, right?
>  "centos/systemd" is something I'd personally love to see be a thing :+1:
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/CentOS/sig-cloud-instance-images/issues/12#issuecomment-77487771

## 

Jim Perrin
The CentOS Project | http://www.centos.org
twitter: @BitIntegrity | GPG Key: FA09AD77

**Comment by tianon** [comment]
Until the systemd hacks aren't hacks anymore, I'm not sure I'm totally
comfortable with them being "official". :confused:

**Comment by jperrin** [comment]
New containers use contain default command.
