### ISSUE TITLE
Official image for CentOS 6.10

### ISSUE THREAD

**Issue by eripa** [CentOS/sig-cloud-instance-images#120]
6.10 was released 3rd of July, 2018. Would it be possible to have official CentOS 6.10 images made available?

https://blog.centos.org/2018/07/release-for-centos-linux-6-10-i386-and-x86_64/

**Comment by itzik-bd** [comment]
+1

**Comment by fhoxh** [comment]
+1

**Comment by jamshid** [comment]
This can be closed, looks like centos:6.10 became available in August.
