### ISSUE TITLE
vim-minimal package in cent os 7 docker image is very old and is potentially unsafe 

### ISSUE THREAD

**Issue by yaduvesh** [CentOS/sig-cloud-instance-images#126]
We are using Centos 7 image from docker hub (centos:7). This comes with vim-minimal package pre-installed.
When we ran our organization's security scan on the docker image, it reported that the package vim-minimal was a very old version (7.4.160) and had security vulnerabilities. It advised to upgrade the version of vim-minimal (upgrade to atleast 7.4.629).

When we try to find the version of the vi inside the centos image's container below is the version reported.
Output of vi --version command below:
----------------------------------------------------------------
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 10 2018 23:54:54)
Included patches: 1-160, 399, 402-403, 1099
-----------------------------------------------------------------

We are using the latest tag of centos from docker hub. It appears that the package vim-minimal is very old (nearly 2 years old)

Is there a way to get an updated centos image which has a newer version of vim-minimal?
Or is it that we (and the security scan) is looking at some wrong version of this package?

**Comment by jperrin** [comment]
Most likely your scanning software does not understand that fixes are done via backports. Please see https://access.redhat.com/security/updates/backporting for details.

If there's a specific CVE that you're concerned about, you can search for it here -> https://access.redhat.com/security/security-updates/#/cve

The short answer is "this is not a bug".
