### ISSUE TITLE
Provide image for 7.6.1810

### ISSUE THREAD

**Issue by ceronman** [CentOS/sig-cloud-instance-images#130]
Version 7.6.1810 has just been [released](https://wiki.centos.org/Manuals/ReleaseNotes/CentOS7.1810). Please provide an image for it.

**Comment by ghost** [comment]
CentOS 7.6 is not released, yet. Latest images are still v7.5.1804 https://wiki.centos.org/Download

Please be patient. After the release the CentOS team will prepare and release an image.

**Comment by adrian-wood** [comment]
Looks like it was released yesterday? The page above hasn't been updated but it now appears in the mirror that we use. http://centos.mirrors.nublue.co.uk/

**Comment by jperrin** [comment]
No. The external mirrors began syncing yesterday so that it could be released and announced today. The announcement literally just went out a few minutes ago.  I'm glad that you're interested in running the latest version, but please have some patience.

**Comment by ghost** [comment]
Release announce for CentOS Linux 7 (1810): https://lists.centos.org/pipermail/centos-announce/2018-December/023082.html

**Comment by askb** [comment]
Looks like the cloud images are still not available online for CentOS 7.6 1810 qcow yet?

**Comment by dsoguet** [comment]
Hello,

I'm looking into https://cloud.centos.org/centos/7/images/ to retrieve CentOS 7.6 1810 qcow but without success.

Do we agree that it is the correct link to retrieve the qcow files?
If yes do you why this version is not available?

Thanks in advance

David
