### ISSUE TITLE
centos 6 "yum -y update" exits with segmentation fault

### ISSUE THREAD

**Issue by valarauca** [CentOS/sig-cloud-instance-images#139]
# Issue

Running `yum -y update` returns an exit code of 139 (128 + 11 = 139, signal 11 = segmentation fault)

This is on `amd64` platform 

## What I expected

Not a segementation fault

## How to reproduce

The follow docker file reproduces the issue:

```dockerfile
FROM centos:6
RUN ["yum", "-y", "update"]
```

When this is built with the command:

```sh
docker build -f $DOCKER_FILE -t centos6_test .
```

it will fail on the `yum -y update` command with non-zero code: 139

**Comment by valarauca** [comment]
As a work around I attempted to install `strace` to get a more detailed error log of the problem fault

Following [this thread from the official forums](https://www.centos.org/forums/viewtopic.php?f=47&t=65700&start=10). This doesn't work as `rpm -iv` will also exit with a segmentation fault when it attempts to download `strace`

**Comment by jperrin** [comment]
What's the host platform you're running this on? What's the storage driver you're using for docker?

**Comment by valarauca** [comment]
Here is my full `docker info` and `docker version` output's

**Output of `docker version`:**

```
Client:
 Version:           18.06.2-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        6d37f41
 Built:             Sun Feb 10 03:47:42 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.2-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       6d37f41
  Built:            Sun Feb 10 03:46:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 49
 Running: 0
 Paused: 0
 Stopped: 49
Images: 401
Server Version: 18.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: a592beb5bc4c4092b1b1bac971afed27687340c5 (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.19.20
Operating System: Debian GNU/Linux buster/sid
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.9GiB
Name: 🤫
ID: RTEG:QILB:L4QZ:4LHR:FKMU:26JJ:4U4E:OGL4:SMQK:AYMH:4VNM:WGJ3
Docker Root Dir: 🤫
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 44
 System Time: 2019-03-13T15:42:38.476389468-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 🤫
Live Restore Enabled: false
```

**Comment by jperrin** [comment]
I'm fairly certain your issue is related to using overlayfs as your storage driver. There are issues in how CentOS 6 is built that mean it doesn't really play nicely with it. If you change the storage driver to loop (slow) or device-mapper/lvm it should work just fine.

**Comment by valarauca** [comment]
I don't encounter this error when working with `centos:7` images. 

Would that be
