### ISSUE TITLE
Only the tags '7' and 'latest' are available on DockerHub for ARM64 architectures

### ISSUE THREAD

**Issue by albertvaka** [CentOS/sig-cloud-instance-images#145]
Only the latest version of the CentOS 7 image (centos:7 and centos:latest) is available for ARM. No minor version images (eg: centos:7.6.1810) are provided, like they are on x86. Is this intended?

**Comment by TommyLike** [comment]
Also wondering if there would be a arm64/v8 version for centos:7.5xxxxx, great thanks!

**Comment by TommyLike** [comment]
@jperrin  do you have any feedback on this issue? 😄

**Comment by jperrin** [comment]
Older versions (such as 7.5.xxxx) aren't supported. We won't be going back to add those specific container versions, no. We should have updates for arm64 for 7.7 and 8 coming very shortly.

**Comment by albertvaka** [comment]
Closing since unfortunately this won't be fixed for 7.x, although for 8.x there are tags already for specific minor versions.
