### ISSUE TITLE
Rpmdb checksum is invalid: dCDPT(pkg checksums)

### ISSUE THREAD

**Issue by r1w1s1** [CentOS/sig-cloud-instance-images#15]
I'm using docker with CentOS 7 and my Dockerfile I'm trying to install "supervisor" package (yum -y install supervisor) but get this error:

Rpmdb checksum is invalid: dCDPT(pkg checksums): bind-libs.x86_64 32:9.9.4-14.el7_0.1 - u

I tried already:

rpm --rebuilddb
yum clean all 
yum -y install supervisor --nogpgcheck

**Comment by r1w1s1** [comment]
I found how to fix.... every line that I use yum to install a package I also insert the "; yum clean all"

example:

RUN yum -y install openssh-server passwd supervisor ; yum clean all

**Comment by jperrin** [comment]
what are you hosting the container on?

**Comment by r1w1s1** [comment]
rancheOS (Vagrant machine)

**Comment by itoed** [comment]
I don't know about those errors you are getting, but you should consider using pip to install supervisor on CentOS.  Not sure about CentOS 7, but supervisor from EPEL for CentOS 6 is really old.

**Comment by r1w1s1** [comment]
supervisor-3.0-1.el7.noarch (EPEL package) this error is not related tp the package itself.... something related to the rpmdb, but I don't know why....

**Comment by dreambrother** [comment]
@ricardsonwilliams 

> I found how to fix.... every line that I use yum to install a package I also insert the "; yum clean all"

this is bad solution, the same as 
`yum -y install openssh-server passwd supervisor || true`

**Comment by r1w1s1** [comment]
@dreambrother yeap....

**Comment by jperrin** [comment]
This appears to be related to the host OS, as on a CentOS 7 box, it installs just fine.

It's worth noting that `yum -y install foo || true` is NOT the same as `yum -y install foo && yum clean all`

The `yum clean all` bits are important as they prevent the yum metadata from being cached in a docker layer, and potentially causing a conflict.

I'm curious if this is related to permissioning within the host (vagrant) OS and if running it with --privileged or otherwise adding capabilities would resolve the issue. Several packages in EL7 require additional functionality that are stock in CentOS but may not be enabled in other distros like ranchos or boot2docker.

**Comment by r1w1s1** [comment]
@jperrin I did some tests using CentOS(Vagrant) as host and works just fine, is something related to the permission/or something on rancherOS. I will "ping" them.

**Comment by jperrin** [comment]
Closing, since it's an upstream issue and not in the container itself.

**Comment by xavierbaude** [comment]
There is a yum patch, simply add this in your Dockerfile  : 

`RUN yum install -y yum-plugin-ovl`

Tested in Centos 7/6 + RHEL 7/6

http://man7.org/linux/man-pages/man1/yum-ovl.1.html

Enjoy Docker/overlay :)

**Comment by jperrin** [comment]
The yum-plugin-ovl package has been a part of the baseline 7 container for some time, and part of the 6 baseline container since 6.8 was released. This shouldn't be necessary if you're using recent images.

**Comment by mboullouz** [comment]
The obscure hack from @ricardson works

**Comment by orodbhen** [comment]
The 7.1 image isn't able to install `yum-plugin-ovl`, because it's not in the repos. So are the older images useless now?

**Comment by jperrin** [comment]
@orodbhen A couple things here:

The 7.1.xx image is a point-in-time image, however the repositories all point to /7/ and so are the current repositories. If you MUST use the older images (I don't recommend this) then you may need to adjust the repositories to your needs.  This should be expected. 

*HOWEVER* the yum-plugin-ovl package is absolutely still in the repositories and is part of the current base image by default. It may or may not be compatible with the version of yum in the old container.

**Comment by orodbhen** [comment]
@jperrin There are a lot of places that `CentOS`/`RHEL` are used where platform upgrades aren't an option. I'm using the image to test software targeted for the `7.1` baseline. 

I pulled the RPM from the `7.3` repo, and installed it directly, and everything worked. Though perhaps disabling `OverlayFS` would be a better solution.

**Comment by knirbhay** [comment]
> I found how to fix.... every line that I use yum to install a package I also insert the "; yum clean all"
> 
> example:
> 
> RUN yum -y install openssh-server passwd supervisor ; yum clean all

You are genius.
