### ISSUE TITLE
sysCentOS 7 

### ISSUE THREAD

**Issue by kimthangatm** [CentOS/sig-cloud-instance-images#16]
On Dockerfile basic with one line: "FROM centos" , I 've build and run images. But on terminal

```
[root@9797bf0f50ae /]# cat /etc/redhat-release 
CentOS Linux release 7.0.1406 (Core) 
[root@9797bf0f50ae /]# systemctl
bash: systemctl: command not found
[root@9797bf0f50ae /]# 
```

**Comment by jperrin** [comment]
Correct. the 7 container does not include systemd by default, as systemd has permissions requirements which mandate that the container must be run in privileged mode by default. 

There are directions for using the 7 container with systemd on https://registry.hub.docker.com/_/centos/
