### ISSUE TITLE
Insufficient space for yum

### ISSUE THREAD

**Issue by duffqiu** [CentOS/sig-cloud-instance-images#17]
When I start a contain with CentOS7, The cmd: yum update return an error:
How to fix it.

But if I use it as a base to build another image, then it is ok.
But I also met the problem as the #15 

---

One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

```
 1. Contact the upstream for the repository and get them to fix the problem.

 2. Reconfigure the baseurl/etc. for the repository, to point to a working
    upstream. This is most often useful if you are using a newer
    distribution release than is supported by the repository (and the
    packages for the previous distribution release still work).

 3. Disable the repository, so yum won't use it by default. Yum will then
    just ignore the repository until you permanently enable it again or use
    --enablerepo for temporary usage:

        yum-config-manager --disable <repoid>

 4. Configure the failing repository to be skipped, if it is unavailable.
    Note that yum will try to contact the repo. when it runs most commands,
    so will have to try and fail each time (and thus. yum will be be much
    slower). If it is a very temporary problem though, this is often a nice
    compromise:

        yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
```

Insufficient space in download directory /var/cache/yum/x86_64/7/base
    \* free   0

**Comment by jperrin** [comment]
what host are you using for this? please provide more information so I can help.

**Comment by duffqiu** [comment]
I finally got the issue. During I built a image, the docker generate a lot temple images which consume almost the disk space of my VM because I use "ctrl + c" to stop the build progress. After I remove all <none> tag images, then there is no problem.

**Comment by jperrin** [comment]
Closing then. thanks for the follow-up

**Comment by ayyilmaz** [comment]
One of the reason of this problem is "  /home/background  " .  I use VestaCp and it backup my website contents for everyday ( approximately each of them is 400 - 500 MB ) and This cause to full of disk.

**Comment by uvolos** [comment]
Try to clear old docker images.
https://www.ibm.com/support/knowledgecenter/en/SSZQDR/com.ibm.rba.doc/LD_cleanupdocker.html
