### ISSUE TITLE
How do you open firewall ports on Docker images?

### ISSUE THREAD

**Issue by buley** [CentOS/sig-cloud-instance-images#2]
Here's what I see at `/etc/sysconfig/iptables` on a fresh install: 

```
$ docker run my/tag cat /etc/sysconfig/iptables
# sample configuration for iptables service
# you can edit this manually or use system-config-firewall
# please do not ask us to add additional ports/services to this default configuration
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
```

I need `80` for a web server. Based on what I've read, I'd want to use: 

> firewall-cmd --zone=public --add-service=http --permanent

Unfortunately there's no firewall-cmd that I can find:

```
$ docker run my/tag which firewall-cmd
which: no firewall-cmd in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```

There's an `/sbin/iptables`; however, there's no service command for a IP tables restart for my rules to take effect. Fortunately, `/sbin/service` comes with installing `initscripts`.

Although you can't change `iptables` rules during a Docker build https://github.com/docker/docker/issues/1916, you can run commands after. I'm using that to update my iptables rules, but on restart I get the following error:

```
$ docker run my/tag service iptables restart
Redirecting to /bin/systemctl restart  iptables.service
/usr/sbin/service: line 79: /bin/systemctl: No such file or directory
```

There is no `/sbin/systemctl` command

```
$ docker run my/tag which systemctl
which: no systemctl in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```

And you cannot install `systemd` because of `fakesystemd`

```
$ docker run my/tag yum install -y systemd
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.unifiedlayer.com
 * epel: mirrors.kernel.org
 * extras: mirror.nwresd.org
 * remi: mirrors.thzhost.com
 * remi-php55: mirrors.thzhost.com
 * remi-php56: mirrors.thzhost.com
 * remi-test: mirrors.thzhost.com
 * rpmforge: mirror.teklinks.com
 * updates: mirror.san.fastserv.com
Resolving Dependencies
--> Running transaction check
---> Package systemd.x86_64 0:208-11.el7_0.2 will be installed
--> Processing Dependency: libcryptsetup.so.4(CRYPTSETUP_1.0)(64bit) for package: systemd-208-11.el7_0.2.x86_64
--> Processing Dependency: dbus for package: systemd-208-11.el7_0.2.x86_64
--> Processing Dependency: acl for package: systemd-208-11.el7_0.2.x86_64
--> Processing Dependency: libwrap.so.0()(64bit) for package: systemd-208-11.el7_0.2.x86_64
--> Processing Dependency: libqrencode.so.3()(64bit) for package: systemd-208-11.el7_0.2.x86_64
--> Processing Dependency: libcryptsetup.so.4()(64bit) for package: systemd-208-11.el7_0.2.x86_64
--> Running transaction check
---> Package acl.x86_64 0:2.2.51-12.el7 will be installed
---> Package cryptsetup-libs.x86_64 0:1.6.3-2.el7 will be installed
---> Package dbus.x86_64 1:1.6.12-8.el7 will be installed
---> Package qrencode-libs.x86_64 0:3.4.1-3.el7 will be installed
---> Package tcp_wrappers-libs.x86_64 0:7.6-77.el7 will be installed
--> Processing Conflict: fakesystemd-1-16.el7.centos.noarch conflicts systemd
--> Finished Dependency Resolution
Error: fakesystemd conflicts with systemd-208-11.el7_0.2.x86_64
 You could try using --skip-broken to work around the problem
** Found 1 pre-existing rpmdb problem(s), 'yum check' output follows:
fakesystemd-1-16.el7.centos.noarch has installed conflicts systemd: fakesystemd-1-16.el7.centos.noarch
```

Here's what the output of `iptables -nvL --line-numbers` looks like on my fresh image:

```
$ docker run -privileged my/tag iptables -nvL --line-numbers
Warning: '-privileged' is deprecated, it will be replaced by '--privileged' soon. See usage.
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination    
```

In the kickstart scripts, the firewall is disabled https://github.com/CentOS/sig-cloud-instance-build/blob/master/docker/centos-7.ks#L7 and firewalld is installed https://github.com/CentOS/sig-cloud-instance-build/blob/master/docker/centos-7.ks#L36 - so perhaps I shouldn't need to open any firewall ports? Firewalld is indeed removed later on https://github.com/CentOS/sig-cloud-instance-build/blob/master/docker/centos-7.ks#L62

```
    # firewalld is necessary for building on centos7 but it is not
    # necessary in the image. remove it and its requirements.
```

**Update** I'm so-far able to confirm that the firewall is down and ports are open when using netcat (`nc -l 80`) and SimpleServer (`python -m SimpleHTTPServer 80`) as a `CMD` to run on `centos:latest`. My issues appear to be  because of how I was running the container (`boot2docker`) on my machine

**Comment by jperrin** [comment]
You don't want to run a firewall inside the container. ssh into containers is generally not advised -> see http://jpetazzo.github.io/2014/06/23/docker-ssh-considered-evil/ 

You should simply just need to expose the ports you want either in your dockerfile or at the commandline. 

The fakesystemd package is there as a stopgap to making systemd work inside a container. see -> http://jperrin.github.io/centos/2014/09/25/centos-docker-and-systemd

**Comment by buley** [comment]
Thanks for your help. I'm used to `iptables` and having most ports closed on vanilla CentOS images. I was having trouble confirming that the port was open and presumed that it was a firewall blocking connections and not the fact that my binary wasn't listening. My apologies for the confusion.

Digging into `iptables` vs `firewalld` was confusing (since neither applied here). The systemd vs. services thing did confuse me further and, to be honest, still does a little bit http://serverfault.com/questions/634277/installing-configuring-and-running-mariadb-in-foreground-on-centos-7-via-docker

**Comment by jperrin** [comment]
if it helps at all, I added this last week after your initial ticket -> https://github.com/CentOS/CentOS-Dockerfiles/tree/master/mariadb/centos7

**Comment by buley** [comment]
> if it helps at all

Why yes, yes it appears it does.

If I can repay you by writing some docs or something, let me know

**Comment by jperrin** [comment]
say nice things on twitter and/or let us know what other containers would be useful to you? I'm in the process right now of publishing several pre-built ones to the docker index. 

Finding out what's actually useful to folks helps immensely.
