### ISSUE TITLE
How to remove systemd-container

### ISSUE THREAD

**Issue by jessfraz** [CentOS/sig-cloud-instance-images#24]
hi!

We build the rpms for the docker project in various containers for each distro version we are releasing. Something changed in the centos 7 container we build in and now when the rpm build script tries to install the dependencies to compile the rpm it gets an error that they all conflict with the already installed "systemd-container"

I need a way to remove that package or force install over it.....

**Comment by jessfraz** [comment]
Also yum remove systemd-container wants to uninstall everything because it seems like every package must rely on it or something....

**Comment by jperrin** [comment]
If you're building against 7 inside the container, you'll need to use the actual systemd package rather than systemd-container. Hopefully this will be sorted in 7.2. 

You'd want to do something like the following:

```
RUN yum -y swap -- remove systemd-container systemd-container-libs -- install systemd systemd-libs

```

**Comment by jessfraz** [comment]
Ok thanks I'll try this

On Friday, July 3, 2015, Jim Perrin notifications@github.com wrote:

> If you're building against 7 inside the container, you'll need to use the
> actual systemd package rather than systemd-container. Hopefully this will
> be sorted in 7.2.
> 
> You'd want to do something like the following:
> 
> RUN yum -y swap -- remove systemd-container systemd-container-libs -- install systemd systemd-libs
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CentOS/sig-cloud-instance-images/issues/24#issuecomment-118370126
> .

## 

Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3

**Comment by jessfraz** [comment]
Also thanks for the speedy response :)

On Friday, July 3, 2015, Jessica Frazelle me@jessfraz.com wrote:

> Ok thanks I'll try this
> 
> On Friday, July 3, 2015, Jim Perrin <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > If you're building against 7 inside the container, you'll need to use the
> > actual systemd package rather than systemd-container. Hopefully this will
> > be sorted in 7.2.
> > 
> > You'd want to do something like the following:
> > 
> > RUN yum -y swap -- remove systemd-container systemd-container-libs -- install systemd systemd-libs
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/CentOS/sig-cloud-instance-images/issues/24#issuecomment-118370126
> > .
> 
> ## 
> 
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3

## 

Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3

**Comment by jperrin** [comment]
doesn't everyone spend their holidays beating on docker?

**Comment by jessfraz** [comment]
But of course :P

On Friday, July 3, 2015, Jim Perrin notifications@github.com wrote:

> doesn't everyone spend their holidays beating on docker?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CentOS/sig-cloud-instance-images/issues/24#issuecomment-118371399
> .

## 

Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3

**Comment by Whitespace** [comment]
@jperrin yes :(
