### ISSUE TITLE
centos:5 image is very slow on Travis CI

### ISSUE THREAD

**Issue by mcanevet** [CentOS/sig-cloud-instance-images#29]
I can't figure out why, but network in centos:5 official image is very slow (~25kb/s) on Travis CI (works fine on my workstation). I don't have any problem using tianon/centos:5.10.

**Comment by jperrin** [comment]
I'm getting normal traffic throughput (currently 14M/s) from the centos:5 image. I'd need significantly more info in order to help, like the host OS, the commands you're running, what version of docker is involved, etc.

**Comment by mcanevet** [comment]
@jperrin well I can't reproduce with a simple test. I guess the issue does not come from the image but from something I do afterwards.
