### ISSUE TITLE
Docker can't find centOS-5 file

### ISSUE THREAD

**Issue by jonathonklem** [CentOS/sig-cloud-instance-images#3]
I've installed docker on an Ubuntu server with:

`apt-get install docker.io
ln -sf /usr/bin/docker.io /usr/local/bin/docker`

I then run
`git clone -b CentOS-5 https://github.com/CentOS/sig-cloud-instance-images.git`

`cd sig-cloud-instance-images/docker`

When I run
`docker build -t apache - < Dockerfile`

I get the following error message: 

Step 2 : ADD centOS-5-20140926_1219-docker.tar.xz /
2014/10/18 01:37:05 centOS-5-20140926_1219-docker.tar.xz: no such file or direct
ory

**Comment by jonathonklem** [comment]
Sorry, false alarm.  

I checked the documentation and I can't build by passing in from STDIN if there's an ADD directive in the docker file like that.

Running `docker build .` worked.

https://docs.docker.com/reference/builder/#add

**Comment by jperrin** [comment]
No worries. as these are what is used to build the official docker images though, I'm wondering why you're doing the work yourself rather than a simple

```
FROM centos:centos5
```

in your Dockerfile.
