### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by pombredanne** [CentOS/sig-cloud-instance-images#34]
How can I get the corresponding source code for an image?

**Comment by pombredanne** [comment]
?

**Comment by jperrin** [comment]
All the sources are on git.centos.org, or available as a source rpm on vault.centos.org

The build guidelines are at https://github.com/CentOS/sig-cloud-instance-build

**Comment by pombredanne** [comment]
@jperrin Thanks for the reply, but it is only mildly helpful ...
How do I figure which sources?
Take for instance the binary centos-6-root.tar.xz at https://github.com/CentOS/sig-cloud-instance-images/tree/20732d1bb34a9aba45c1c6f41576ed6bf3d8c619/docker
How can I collect the corresponding sources if I redistribute an image based on that such that among other things  that I can meet my GPL obligations?

**Comment by pombredanne** [comment]
@jperrin I would appreciate if you could reopen this btw.

**Comment by pombredanne** [comment]
btw, where do I find the licensing information in the images?

**Comment by jperrin** [comment]
Figuring out which source you need is up to you. There are several ways to do it. For example, you could use rpm -qai to list the rpms and determine the source rpm needed. This will change as the images get updates. The default project license is GPLv2, however the packages contain their own licenses. 

The license and EULA is listed on the mirror under the appropriate version (standard location for fedora/centos/rhel). For example -> http://mirror.centos.org/centos-7/7/os/x86_64/

**Comment by pombredanne** [comment]
@jperrin figuring out which source you put in the images you redistribute is not up to me but up to you IMHO: you are redistributing this in the first place, are you not? I do not want to be a pain there, but getting the sources is straightforward and clear for a Centos ISO distro proper and completely opaque for these images. 

FWIW, there is even not a single copy of the GPL (and other licenses) in the image: so the packages in the image do not contain their own licenses as fas as I can see.

**Comment by pombredanne** [comment]
On the licenses, I can see the reason why they are no longer there: https://github.com/CentOS/sig-cloud-instance-build/blob/b4ea7528b90065db1d5c414ecc38cd1dfa389a9b/docker/centos-6.6.ks#L77
You are effectively removing all and any doc, including any license texts?

**Comment by hughesjr** [comment]
We provide every piece of source code here:
http://vault.centos.org/

You have to find the pieces that you want .. if it is from, for example, CentOS 7, it would be here:

http://vault.centos.org/centos/7/

It is not up to us to also find the source code for you.  We have no idea what you might want to redistribute.  So, if you want source code, then you look through the tree and find what you want.  You need to do the leg work to figure out what you are actually using (ie rpm -qpi <rpm_name> and figure out the SRPM name and find it in the public posted source code).

**Comment by jperrin** [comment]
You mentioned you're concerned about YOUR GPL compliance for what you ship. That is entirely your responsibility. GPL compliance for the distribution is something we take seriously, which is why the source is identical to the distribution source. We provide full sources in two separate areas, via two separate methods. Stripping documentation is a commonly used method for making the containers smaller. without doing this, the base container balloons to roughly 500MB or more. The package metadata still contains the license information, and a simple yum command reinstalls the documentation with license. 

You seem to be making a large deal about a non-issue for some reason I cannot fathom.

**Comment by hughesjr** [comment]
As to the license for the distro's or images .. we use the same packages in our images as we ship in our distro's .. and we have pointed you to where you can find them.  No matter how you get CentOS from us .. the EULA and the License is the same and can be found here:

http://mirror.centos.org/centos/7/os/x86_64/  

(For CentOS 7) .. change the 7 to a 6 or a 5 for CentOS-6 or CentOS-5

**Comment by hughesjr** [comment]
If you are concerned about trademark issues .. we have that here:

https://www.centos.org/legal/trademarks/

**Comment by pombredanne** [comment]
@hughesjr @jperrin Thanks for chiming in. Well I guess there is much more footwork to do than there is on a regular Centos distro ISO. The thing that does not help is that an image tag points to a rolling build, so depending on when an image was pulled matters as the content of the same tag will have evolved over time, and there is no easy way to get from an image tag/id to its actual exact build script and initial rootfs.

I guess I will have just have to throw a quick script to get the sources and that for every image, though I wished it would have been simpler!

FWIW, I still think you should revisit stripping all the docs: as much as I appreciate the size argument  not having even a basic GPL text feels kinda odd: but this is your call.
Seize the day!

**Comment by jperrin** [comment]
We do point-in-time tags as well, you just need to be sure to update them as vulnerabilities are discovered. The point-in-time releases correspond to the install media (or just the OS tree, without updates). These are the 6.6, 6.7, 7.0.1406 tags, etc.

**Comment by pombredanne** [comment]
@jperrin thanks!

**Comment by pombredanne** [comment]
I see that the docs (including the license texts) are no longer stripped from the images as they should per https://github.com/CentOS/sig-cloud-instance-build/commit/a1dccf8f9ddb17e550cb6fadf6471e4c50360384#diff-16b3ea49a39f077881744a1b56722aff

Thank you.

**Comment by pombredanne** [comment]
actually this is not trye: --excludedocs means that ALL your base images are not even in basic compliance with the GPL and most every other FLOSS licenses

**Comment by pombredanne** [comment]
Just for the record, all this is all fixed now and no longer an issue since all license texts are now in the base images `/usr/share/licenses/<package name>/...`
Thank you ++
