### ISSUE TITLE
Unable to install docker when using the latest centos7 image due to systemd file conflicts

### ISSUE THREAD

**Issue by sidharta-s** [CentOS/sig-cloud-instance-images#38]
The issue can be reproduced using the simple Dockerfile shown below. 

<pre><code>q (07:09:57) ~/test$ cat Dockerfile.test
FROM docker.io/centos:centos7
RUN yum install -y docker
CMD ["/bin/bash"]
q (07:10:03) ~/test$ docker build -f Dockerfile.test .</code></pre>

This results in errors like these :

<pre><code>Transaction check error:
  file /usr/lib64/libsystemd-daemon.so.0 from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/libsystemd-id128.so.0 from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/libsystemd-journal.so.0 from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/libsystemd-login.so.0 from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/libudev.so.1 from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/security/pam_systemd.so from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64</code></pre>

In case it matters, I am running docker engine 1.9.0 on CentOS 7.1 .

**Comment by jperrin** [comment]
Correct. This is caused by the removal of systemd-container from 7.2. Do a new `docker pull centos:7` to resolve it.

**Comment by sidharta-s** [comment]
I'll try this out, thanks!

**Comment by buley** [comment]
Is there a webhook anywhere we can use to update our Centos base images when a build is shipped?

**Comment by jperrin** [comment]
I know there have been several attempts at submitting a feature like this to docker, but I don't think any of them have been merged in yet. I would check with docker folks to see.

**Comment by buley** [comment]
Thanks @jperrin. I'll investigate. I use a CentOS base image to which add my user needs, etc. Anything that ran `yum update` in the Dockerfile broke following this change, since my base image wasn't updated but those containers using it were updating their packages.

**Comment by sidharta-s** [comment]
It looks like using an older image 7.1 image causes issues when installing docker. This fails : 

```
q (19:58:30) ~/test$ cat Dockerfile.test
FROM docker.io/centos:centos7.1.1503
RUN yum install -y docker-1.8.2
CMD ["/bin/bash"]
q (19:58:32) ~/test$ docker build -f Dockerfile.test .
```

**Comment by jperrin** [comment]
point-in-time releases will require added attention, yes. This is because the 7.1.1503 container is trying to pull from current repositories. You'll have to apply updates and work around systemd-container vs systemd dep issues.

**Comment by jay-johnson** [comment]
Had to update my base image like @buley. Thanks for the fix @jperrin
