### ISSUE TITLE
tar utility missing in centos6 base image

### ISSUE THREAD

**Issue by pgentile** [CentOS/sig-cloud-instance-images#4]
The centos6 base image doesn't contain an important utility, the `tar` command.

**Steps to reproduce :**

Start an interactive `bash` session with the `docker run` command :

```
docker pull centos
docker run -i -t centos:centos6 /bin/bash
```

In opened session, try to execute the `tar` command :

```
bash-4.1# tar
bash: tar: command not found
```

The RPM containing the `tar` command is not installed on the image :

```
bash-4.1# rpm -q -a | grep ^tar
```

**Comment by jperrin** [comment]
correct. These are minimal images built from the kickstarts in 
`https://github.com/CentOS/sig-cloud-instance-build`

They're designed to be quite small so not every command is available. They can be installed via yum just fine.

**Comment by pgentile** [comment]
Hi Jim,

Thanks for the answer. I will use `yum` to install `tar`.
