### ISSUE TITLE
dbus.service failes with centos7.2.1511 image

### ISSUE THREAD

**Issue by aquister** [CentOS/sig-cloud-instance-images#41]
systemd fails to launch dbus.service. 

```
Dec 17 08:21:11 centos-7-x64 dbus-daemon[41]: Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
```

Adding following to dockerfile fixes the issue:

```
RUN mkdir -p /etc/selinux/targeted/contexts/
RUN echo '<busconfig><selinux></selinux></busconfig>' > /etc/selinux/targeted/contexts/dbus_contexts
```

**Comment by vlisivka** [comment]
Thanks for workaround.

**Comment by jperry** [comment]
Doesn't seem to work for me

```
[root@0e27515831d7 /]# cat /etc/selinux/targeted/contexts/dbus_contexts
<busconfig><selinux></selinux></busconfig>[root@0e27515831d7 /]#
```

```
           ---- Begin output of /sbin/service rabbitmq-server restart ----
           STDOUT: Restarting rabbitmq-server (via systemctl):  [FAILED]
           STDERR: Failed to get D-Bus connection: Operation not permitted
           Failed to get D-Bus connection: Operation not permitted
           ---- End output of /sbin/service rabbitmq-server restart ----
```

**Comment by logicalup** [comment]
why was this closed? this is still an issue

**Comment by jperrin** [comment]
The 7.2.1511 container is a minor release, and doesn't get updates like the 7 or latest containers.

**Comment by bartmcleod** [comment]
Still an issue with the centos:7.4.1708 image.

**Comment by bartmcleod** [comment]
And with centos:latest

**Comment by kuncao** [comment]
any one know how to resolve the issue?
cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
thanks a lot

**Comment by bartmcleod** [comment]
It seems that if you encounter an error like this, related to systemctl or service, you are trying to use docker the wrong way. Ideally the container should be one process, possibly a process normally running as a service, now running as a container process. If you need to restart it, you have to restart the container. Any config changes you want, should be done through a Dockerfile (a build).

**Comment by kuncao** [comment]
solution:with -rm optiion such as
docker run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro --privileged -d -p 18002:18002 -p 1127:1127 -p 2222:22 --rm --ip 172.20.0.3 --net smbridge -h SmServer --shm-size=36G --name secom secom:v1
[root@SmServer packagessm]# pwd
/root/packagessm
[root@SmServer packagessm]# ls
PreInstall_CentOS7.1.zip SecoManager_5.1.0.B010_ALL_install_config.zip
[root@SmServer packagessm]# systemctl
UNIT LOAD ACTIVE SUB DESCRIPTION
dev-xvda1.device loaded activating tentative /dev/xvda1
-.mount loaded active mounted /
dev-mqueue.mount loaded active mounted POSIX Message Queue File System
etc-hostname.mount loaded active mounted /etc/hostname
etc-hosts.mount loaded active mounted /etc/hosts
etc-resolv.conf.mount loaded active mounted /etc/resolv.conf
sshd-keygen.service loaded active exited OpenSSH Server Key Generation
sshd.service loaded active running OpenSSH server daemon
systemd-journald.service loaded active running Journal Service
systemd-tmpfiles-setup.service loaded active exited Create Volatile Files and Directories
-.slice loaded active active Root Slice
system.slice loaded active active System Slice
dbus.socket loaded active listening D-Bus System Message Bus Socket
systemd-journald.socket loaded active running Journal Socket
systemd-shutdownd.socket loaded active listening Delayed Shutdown Socket
basic.target loaded active active Basic System
local-fs.target loaded active active Local File Systems
multi-user.target loaded active active Multi-User System
paths.target loaded active active Paths
slices.target loaded active active Slices
sockets.target loaded active active Sockets
swap.target loaded active active Swap
sysinit.target loaded active active System Initialization
timers.target loaded active active Timers
systemd-tmpfiles-clean.timer loaded active waiting Daily Cleanup of Temporary Directories
LOAD = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB = The low-level unit activation state, values depend on unit type.
25 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
-------------other information----------------
--------------base image dockerfile----------
FROM centos:7
ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in ; do [ $i == 
systemd-tmpfiles-setup.service ] || rm -f $i; done); 
rm -f /lib/systemd/system/multi-user.target.wants/;
rm -f /etc/systemd/system/.wants/;
rm -f /lib/systemd/system/local-fs.target.wants/; 
rm -f /lib/systemd/system/sockets.target.wants/udev; 
rm -f /lib/systemd/system/sockets.target.wants/initctl; 
rm -f /lib/systemd/system/basic.target.wants/;
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]
#######added 20180322
ADD cmd.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/cmd.sh
CMD ["/usr/local/bin/cmd.sh"]
#######added 20180322
#######changed 20180322
#CMD ["/usr/sbin/init"]
#######changed 20180322

cmd.sh file when compile base image
#!/bin/bash
exec /usr/sbin/init # To correctly start D-Bus thanks to https://forums.docker.com/t/any-simple-and-safe-way-to-start-services-on-centos7-systemd/5695/8

-----------------------business dockerfile------------------------------------------
########################## build secomanager dockerfile ###########################
FROM local/c7-systemd
MAINTAINER caokun caokun.nj@huawei.com
ENV container docker
ENV TZ Asia/Shanghai
ENV http_proxy c00286473:password@proxyus3.huawei.com:8080/
ENV https_proxy c00286473:password@proxyus3.huawei.com:8080/
ENV all_proxy c00286473:password@proxyus3.huawei.com:8080/
ENV no_proxy=127.0.0.1,.huawei.com,localhost,local,.local,10.120.165.217,*.huawei.com
RUN yum install -y openssh-server vim telnet sudo wget unzip tar gcc openssl lsof service compat-libstdc++-33 systemctl strace
RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
RUN useradd guest
RUN echo "guest:guest!@#" | chpasswd
RUN echo "guest ALL=(ALL) ALL" >> /etc/sudoers
RUN echo "root:Mylinux1" | chpasswd
RUN sed -i '1s/^/set encoding=utf-8\n/' /etc/vimrc 
&& echo "set hls" >> /etc/vimrc 
&& echo "set expandtab" >> /etc/vimrc 
&& echo "set sw=4" >> /etc/vimrc 
&& echo "set tabstop=4" >> /etc/vimrc
RUN sudo mkdir /root/packagessm
ADD files/PreInstall_CentOS7.1.zip /root/packagessm/
ADD files/SecoManager_5.1.0.B010_ALL_install_config.zip /root/packagessm/
WORKDIR /root/packagessm
#WORKDIR /root
RUN sudo mkdir /var/run/sshd
#############for ssh
#EXPOSE 22
#ENTRYPOINT /usr/sbin/sshd -D
#############for ssh
CMD ["/usr/sbin/init"]

command to build base image
docker build --rm -t local/c7-systemd .
command bo build business image
docker build --rm -t secom:v1 .

other information
[root@szvphicpra31005 Sm_Docker]# docker --version
Docker version 17.03.0-ce, build 3a232c8
docker 内的os
[root@SmServer packagessm]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)

**Comment by wusto** [comment]
This problem might also be related to file permissions problems for /etc/selinux/config.

Make sure that this file is world-readable (e.g. 0444). dbus takes "targeted" as standard SELINUXTYPE if /etc/selinux/config is not readable for its UID/GID.
