### ISSUE TITLE
centos:7 cannot find command /usr/bin/which after update 12/29/2015

### ISSUE THREAD

**Issue by asdfsx** [CentOS/sig-cloud-instance-images#43]
``` sh
$ docker run -it --rm centos:7 which
exec: "which": executable file not found in $PATH  
```

I need to execute some shell script which need to use "which" command. And now, when I execute the script in the container I get errors.

**Comment by jperrin** [comment]
There are a few packages that were removed from the updated base container as an effort to standardize. Info is here -> https://github.com/CentOS/sig-cloud-instance-images/issues/40

You can work around this simply by  adding `RUN yum -y install which && yum clean all` to your Dockerfile.

**Comment by asdfsx** [comment]
Thx very much ~~~ but it really make it uncomfortable, I need to rebuild a lot of images which based on centos

**Comment by asdfsx** [comment]
@jperrin by the way, I found that systemd is still in the image, do we need it inside a docker image? 
I build a mesos 0.26 image but can not use it. Because I found the latest mesos-slave will check whether there is systemd in the system. If systemd exists, it will try to use systemd. But as you know, the container won't start systemd, so every time I get somethink like this 

``` sh
I1231 07:01:54.959487    14 systemd.cpp:128] systemd version `219` detected
Failed to get D-Bus connection: No such file or directory
E1231 07:01:54.964546    14 shell.hpp:90] Command 'systemctl start mesos_executors.slice' failed; this is the output:
Failed to create a containerizer: Could not create MesosContainerizer: Failed to create launcher: Failed to start 'mesos_executors.slice': Failed to start systemd slice `mesos_executors.slice`: Failed to execute 'systemctl start mesos_executors.slice'; the command was either not found or exited with a non-zero exit status: 1 
```

Maybe I should remove systemd by my self, but how?

**Comment by jperrin** [comment]
Several packages in el7 depend on systemd, so it cannot be removed from the container. in 7.0.1406 we did this with fakesystemd, and in 7.1.1503 it was changed to systemd-container. Now systemd has improved enough that it's actual systemd. 

You can absolutely use systemd in a container and it will run just fine. You need to change the CMD, and a few other bits, but it's pretty simple to make happen.

**Comment by asdfsx** [comment]
@jperrin So you mean I can start some services in docker by using systemd? That's an interesting news! Could you plz tell me how?

**Comment by jperrin** [comment]
Mostly like this -> https://hub.docker.com/_/centos/

since systemd is default in the container, you can skip the `yum swap foo` line in the directions.
