### ISSUE TITLE
Adding EPEL Repository to CentOS 6.7 Image

### ISSUE THREAD

**Issue by CIS-gvoit** [CentOS/sig-cloud-instance-images#44]
Hi all,

I'm working on Dockerizing a Ruby Application running on Ruby 2.2.3. The application works with PDF's and the packages required to work with the PDF's are contained within the EPEL repository.

Below is my Dockerfile

```
FROM centos:6.7

RUN yum update -y

# Install Ruby & Dependencies
RUN yum install -y gcc-c++ patch readline readline-devel zlib zlib-devel
RUN yum install -y libyaml-devel libffi-devel openssl-devel make
RUN yum install -y bzip2 autoconf automake libtool bison iconv-devel sqlite-devel

# Install utils
RUN yum install -y curl
RUN yum install -y wget
RUN yum install -y which
RUN yum install -y tar

# Install RVM
RUN curl -sSL https://rvm.io/mpapis.asc | gpg --import -
RUN curl -L get.rvm.io | bash -s stable

# Configure RVM
RUN source /etc/profile.d/rvm.sh -c rvm reload rvm requirements run rvm install 2.2.3 rvm use 2.2.3 --default

# Prerequisite installation for PDF processing
RUN yum install -y ImageMagick-devel

# Attempt to add EPEL Repository
RUN rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm

# Leptonica-devel / tesseract-devel are the packages that require EPEL repository
RUN yum install -y leptonica-devel tesseract-devel
RUN yum install -y libgcj
RUN yum install -y https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/pdftk-2.02-1.el6.x86_64.rpm
RUN yum install -y ImageMagick
```

I have been searching for several hours for a way to add the EPEL repository to the CentOS 6.7 base image but without success.

Thanks

**Comment by jperrin** [comment]
you can simply do

`RUN  yum -y install epel-release`

we do this for a number of example containers

**Comment by CIS-gvoit** [comment]
Thanks for the quick response time! This worked. My mistake was that in my attempted fixes, I had inadvertently "overlapped" a few of them by trying to install non-EPEL packages (after successfully installing the EPEL repo). Sorry about that! Thanks for the quick response.
