### ISSUE TITLE
"License=GPLv2" tag on Docker images

### ISSUE THREAD

**Issue by dmaze** [CentOS/sig-cloud-instance-images#48]
If I `docker inspect centos:centos6`, it says (in part) `"License": "GPLv2"`.  Do you mean this to imply that the container itself is GPL'd, with the various things that implies?  If I say `FROM centos:centos6` in my Dockerfile, can I eventually be obligated to come up with complete source for every package in CentOS to a potential downstream recipient of the container image?

**Comment by jperrin** [comment]
The default license for the CentOS Project is GPLv2, We include this license in the install media as well -> http://mirror.centos.org/centos-7/7/os/x86_64/GPL

In short, the packages are covered under their respective licenses, be it gpl, bsd, mit, apache, etc. The license here is meant to reflect the same license as the install media and project license. 

Whether you would be obligated to come up with sources is between you and your lawyer. My personal (and non-legally binding) opinion is that you could simply point to the centos mirrors for the sources of packages included in the base container. You would be responsible for the licensing/sourcing of anything you add to that though.

**Comment by dmaze** [comment]
Is your intent that derived containers also have GPLv2 applied to them?  If I write a Dockerfile like

``` docker
FROM centos:centos6
COPY /opaque-binary /
CMD ["/opaque-binary"]
```

that would require me to also redistribute the Dockerfile and the opaque binary itself to others who asked for it; would the binary itself also fall under the GPL's terms?  If it were other open-source software, would it be required to have a compatible license that would allow the GPL's restrictions?

**Comment by jperrin** [comment]
My intent is to provide the same licensing as a standard 'traditional' install of centos. Nothing more, nothing less.
