### ISSUE TITLE
Updated 6.7 image?

### ISSUE THREAD

**Issue by ghost** [CentOS/sig-cloud-instance-images#49]
I need a 6.7 image with the recent glibc security fix.  It's not clear if the 6.7 image contains it - would it be possible to get an updated image if the current one doesn't the fix and either case could you update label for it too?

Thanks.

**Comment by jperrin** [comment]
The minor image tags such as 6.7 do not get updates. They are created to
mirror the install media. If you need an updated container, you should use
the 6 image.

**Comment by mcummingsbit9** [comment]
OK, just to clarify then, what is the proper way to ensure that I have a CentOS 6.7  image with the glibc fix?  

* pull down the 6 image and then the 6.7 image
* just use the 6.7 image and update glibc in my local copy (or in Dockerfiles that reference that image)
* something else
