### ISSUE TITLE
Full systemd Dockerfile example

### ISSUE THREAD

**Issue by buley** [CentOS/sig-cloud-instance-images#53]
Does anyone have a full systemd base container Dockerfile that they can share? I attempted to follow the steps outlined on Hub but ran into issues. I'm [working to verify](https://github.com/nginxinc/nginx-amplify-agent/issues/13) for nginx that their Amplify install script works on CentOS.

```
Step 5 : RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i ==
 ---> Running in e9ca5b601dd7
/bin/sh: -c: line 1: syntax error: unexpected end of file
```

From Hub comments, it's possibly a newline problem:

<img width="1083" alt="screen shot 2016-03-29 at 4 49 49 pm" src="https://cloud.githubusercontent.com/assets/86985/14127630/54abd290-f5ce-11e5-86c4-76e27e67e329.png">

**Comment by jperrin** [comment]
That is indeed a newline issue. The `RUN (cd ...`  line continues to the line below. So it appears that the hub's website is breaking it a bit.

**Comment by buley** [comment]
Thanks for confirming @jperrin. The nginx folks want me to have a systemd container and I'm trying to wrap my head around how to add this to a base image.

**Comment by jperrin** [comment]
FYI, there is now a centos/systemd container you can use

https://hub.docker.com/r/centos/systemd/
