### ISSUE TITLE
Update images at docker hub for fixing #60

### ISSUE THREAD

**Issue by norrs** [CentOS/sig-cloud-instance-images#61]
Accordingly to #60 , latest images on docker hub refuses ssh login. 

This got fixed in https://github.com/CentOS/sig-cloud-instance-build/commit/36473e7c408781f578fe4d4b2f21d14b4a9c2708 , but docker hub has not been updated in 18 days: https://hub.docker.com/r/library/centos/tags/

**Comment by jperrin** [comment]
Correct. I just pushed the kickstart patch last night. I haven't built the corresponding container yet.

**Comment by jperrin** [comment]
Container updated, pull request submitted, fixed when  https://github.com/docker-library/official-images/pull/1962 merges
