### ISSUE TITLE
ppc64le/centos:7 - yum permissions issues

### ISSUE THREAD

**Issue by paulbsch** [CentOS/sig-cloud-instance-images#87]
I'm seeing some weird issues when trying to use the ppc64le/centos:7 image:

```
$ sudo docker run -it --rm ppc64le/centos:7 /bin/bash
[root@284ced70a8ff /]# yum -y update
error: db5 error(1) from dbenv->open: Operation not permitted
error: cannot open Packages index using db5 - Operation not permitted (1)
error: cannot open Packages database in /var/lib/rpm
CRITICAL:yum.main:

Error: rpmdb open failed
```

It seems specific to this image as I have not run into this issue when using Fedora ppc64le images on the same host machine.  Or CentOS 7 x86_64 docker images on a separate x86_64 host machine.

If I run the ppc64le/centos:7 image as privileged, however, the issue seems to go away.

**Comment by newjcj** [comment]
who are you?




发自网易邮箱大师


On 06/22/2017 05:56，Paul B Schroeder<notifications@github.com> wrote：

I'm seeing some weird issues when trying to use the ppc64le/centos:7 image:

$ sudo docker run -it --rm ppc64le/centos:7 /bin/bash
[root@284ced70a8ff /]# yum -y update
error: db5 error(1) from dbenv->open: Operation not permitted
error: cannot open Packages index using db5 - Operation not permitted (1)
error: cannot open Packages database in /var/lib/rpm
CRITICAL:yum.main:

Error: rpmdb open failed


It seems specific to this image as I have not run into this issue when using Fedora ppc64le images on the same host machine. Or CentOS 7 x86_64 docker images on a separate x86_64 host machine.

If I run the ppc64le/centos:7 image as privileged, however, the issue seems to go away.

**Comment by jperrin** [comment]
@newjcj that's a fairly inappropriate response to an issue.

@paulbsch can you check to see if yum-plugin-ovl is included in this container? This is symptomatic of a problem caused when this package is missing, but there are other causes.

**Comment by newjcj** [comment]
do you have skype or facebook number? i add you

**Comment by newjcj** [comment]
i want add you for skype or facebook




发自网易邮箱大师


On 06/22/2017 12:31，Jim Perrin<notifications@github.com> wrote：

@newjcj that's a fairly inappropriate response to an issue.

@paulbsch can you check to see if yum-plugin-ovl is included in this container? This is symptomatic of a problem caused when this package is missing, but there are other causes.

**Comment by paulbsch** [comment]
Hi @jperrin ..  It does appear to be installed:

```
[root@32a0e422b624 /]# ls /usr/lib/yum-plugins/ovl.py*
/usr/lib/yum-plugins/ovl.py   /usr/lib/yum-plugins/ovl.pyo
/usr/lib/yum-plugins/ovl.pyc
```

**Comment by jperrin** [comment]
hmm. I'll have to talk with the folks who built this then to see what's going on. 

To get a bit more information, can you provide a bit more detail about the host? 

what's the output of `docker version` and/or `docker info`

**Comment by paulbsch** [comment]
Of course.  Thanks @jperrin ...  Here it is:

```
otto@dal2ppc10p2:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
otto@dal2ppc10p2:~$ sudo docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:34:35 2017
 OS/Arch:      linux/ppc64le

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:34:35 2017
 OS/Arch:      linux/ppc64le
otto@dal2ppc10p2:~$ sudo docker info
Containers: 125
 Running: 0
 Paused: 0
 Stopped: 125
Images: 1054
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1111
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: ppc64le
CPUs: 160
Total Memory: 1022 GiB
Name: dal2ppc10p2
ID: QL5U:GS6Q:V4L6:ELJ7:W3NB:XWV7:TZX7:YLT7:AOTV:ZK33:OP3R:XGMR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by paulbsch** [comment]
Is there any status info on this, @jperrin?  It looks like there hasn't been an update to the image.  I'm a bit surprised as this seems to be a critical issue.

**Comment by jperrin** [comment]
You're using it on the AUFS storage driver, which is feature incomplete and missing many things that many distributions require (file system capabilities). If you can try it with a different storage driver such as the lvm, overlay or even loopback, you'll probably find that it works.

**Comment by paulbsch** [comment]
Ah!  I should have thought to try that sooner.  Switching to overlay2 seems to have resolved this.
Thanks!
