### ISSUE TITLE
cant pull centos:7.4.1708, image not found

### ISSUE THREAD

**Issue by mgrybyk** [CentOS/sig-cloud-instance-images#91]
Hi,

cant see 7.4.1708 here: https://registry.hub.docker.com/v2/repositories/library/centos/tags/

but it is mentioned here: https://hub.docker.com/_/centos/

can you please fix?
Thanks

**Comment by jperrin** [comment]
You'd need to file this against https://github.com/docker-library/official-images 

I've submitted the builds to them, but I don't have access or authority on their network/cdn.

**Comment by mgrybyk** [comment]
Just wanted to mention that 7.4.1708 is there now, but 7.3 is missing...

**Comment by jperrin** [comment]
All I can do is tell you that the tags are still in the proper file->  https://github.com/docker-library/official-images/blob/master/library/centos

Did you file this as an issue with the the docker-library folks?

**Comment by mgrybyk** [comment]
No, I didn't
